name: Generate Snake Animation

on:
  schedule:
    # Executa diariamente
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Baixa o repositório
      - name: Checkout
        uses: actions/checkout@v2

      # Gera a cobrinha
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: victorllcs
          output_path: dist/github-contribution-grid-snake.svg

      # Publica a cobrinha no GitHub Pages
      - name: Push Snake Animation to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
